// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main documentation sidebar
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/overview',
      ],
    },
    {
      type: 'category',
      label: 'Whitepaper',
      items: [
        'whitepaper/introduction',
        'whitepaper/spiritual-foundation',
      ],
    },
    {
      type: 'category',
      label: 'Tokenomics',
      items: [
        'tokenomics/overview',
        'tokenomics/psilo-token',
      ],
    },
    {
      type: 'category',
      label: 'DAO Governance',
      items: [
        'governance/overview',
      ],
    },
    {
      type: 'category',
      label: 'NFT Ecosystem',
      items: [
        'nfts/overview',
      ],
    },
    {
      type: 'category',
      label: 'Sacred Altar',
      items: [
        'sacred-altar/overview',
      ],
    },
    {
      type: 'category',
      label: 'Technical Architecture',
      items: [
        'architecture/overview',
      ],
    },
  ],

  // Tutorial sidebar for dApp usage
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial',
    },
  ],
};

export default sidebars;
