// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main documentation sidebar
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/overview',
      ],
    },
    {
      type: 'category',
      label: 'Whitepaper',
      items: [
        'whitepaper/introduction',
        'whitepaper/spiritual-foundation',
      ],
    },
    {
      type: 'category',
      label: 'Principles',
      items: [
        'principles/overview',
        'principles/generosity',
        'principles/truth',
        'principles/compassion',
        'principles/transparency',
        'principles/communion',
        'principles/regeneration',
      ],
    },

    {
      type: 'category',
      label: 'Tokenomics',
      items: [
        'tokenomics/overview',
        'tokenomics/psilo-token',
        'tokenomics/mdao-token',
        'tokenomics/etho-token',
        'tokenomics/psd-stablecoin',
        'tokenomics/dm-token',
        'tokenomics/token-economics-review',
      ],
    },
    {
      type: 'category',
      label: 'DAO Governance',
      items: [
        'governance/overview',
      ],
    },
    {
      type: 'category',
      label: 'NFT Ecosystem',
      items: [
        'nfts/overview',
        'nfts/mushroom-breeding',
        'nfts/pob-nfts',
      ],
    },
    {
      type: 'category',
      label: 'Sacred Altar',
      items: [
        'sacred-altar/overview',
      ],
    },
    {
      type: 'category',
      label: 'Technical Architecture',
      items: [
        'architecture/overview',
        'architecture/ton-layer',
        'architecture/aleo-privacy-layer',
      ],
    },
    {
      type: 'category',
      label: 'For Developers',
      items: [
        'developers/smart-contracts',
      ],
    },
    {
      type: 'category',
      label: 'SyncDocs 2025-10-24',
      items: [
        {
          type: 'autogenerated',
          dirName: 'SyncDocs2025_10-24',
        },
      ],
      collapsed: false,
    },
    'security',
    'roadmap',
    'faq',
    'glossary',
  ],

  // Tutorial sidebar for dApp usage
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial',
    },
  ],
};

export default sidebars;
